services:
  - type: web
    name: slack-exporter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SLACK_USER_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
